from django.db import models
from vendor_profile.models import Vendor 
from django.core.exceptions import ValidationError

class PurchaseOrder(models.Model):
    po_number = models.CharField(max_length=50, unique=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    order_date = models.DateTimeField()
    delivery_date = models.DateTimeField()
    items = models.JSONField()
    quantity = models.IntegerField()
    status = models.CharField(max_length=50)
    quality_rating = models.FloatField(null=True, blank=True)
    issue_date = models.DateTimeField()
    acknowledgment_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.po_number

    def clean(self):
        super().clean()
        if self.quality_rating is not None and self.quality_rating > 5:
            raise ValidationError("Quality rating cannot be more than 5.")